### ISSUE TITLE
issues in running app.py

### ISSUE THREAD

**Issue by brahmanggi** [klemmari1/tg_vava_bot#1]
`Traceback (most recent call last):
  File "./app.py", line 15, in <module>
    bot = tgbot.TgbotConnection(os.environ["BOTTOKEN"])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'TOKEN' `

**Comment by klemmari1** [comment]
You need to add ENV variables to your environment:
- TOKEN from Telegram Bot API and HOOK for the Telegram hook url.
- G_KEY and G_CX from Google Search API
